### ISSUE TITLE
Hash code is out of date

### ISSUE THREAD

**Issue by mgroves** [fieldstonesoftware/laravel-couchbase-demo#4]
Need a more evergreen approach and/or remove the checksum check?

https://github.com/fieldstonesoftware/laravel-couchbase-demo/blob/d3d94bd27ddadee3b4a155887f3dc4dac2a4da24/scripts/Docker/php-fpm/Dockerfile#L19

**Comment by jrlawhorne** [comment]
Thanks Matt! I removed the hash check. It's a security measure and, in my opinion, overkill for a non-production environment.
